### PR TITLE
In check

### PR DESCRIPTION
**Pull request by ghost**
- Removed top notice and alert from application.html.erb because it displays in show.html.erb.
- Added top notice and alert to static_pages/index.html.erb because the notices seem to be wanted there.
- Added method to check if king is in check in game.rb
- Added notice to flash below the board in the show method in games_controller.rb if the king is in check. Moving the pieces current reload the page, which checks the method from the Game model.

### CODE REVIEW

**Comment by mattschmitter** [comment]
I think this looks pretty good.  My only comment about the notice and alert from application.html.erb is that Devise will throw others up on the sign up/in pages as well, so I think we might need to have it there.  I think we could hide them on the game show page by targeting them with a css display: none if we think it's better to have them below the board.

**Comment by ghost** [comment]
It's still showing on top of the page when I sign up and sign in on my end. The display below the show page was already there. I'm not sure who put it there, but I ended up just using it. Let me know if you guys want to stick with the one on top, which displays under the blue header or the one under the board.

**Comment by ghost** [comment]
- Re-added top notice and alert from application.html.erb.
- Removed top notice and alert to static_pages/index.html.erb.
- Added new flash game_alert for the alerts under the board.

**Comment by ghost** [comment]
The checkmate uses the will_cause_check?(x, y) method. The king is in checkmate when will_cause_check? returns true for all the possible positions around the king. This was similar to the idea for the initial king_in_check? method, but I went back and did a loop per our conversation on Hangouts.
- Added checkmate logic to game.rb
- Updated display for check, checkmate, and nothing in games_controller.rb

**Comment by mattschmitter** [comment]
Awesome!  :thumbsup:

**Pull request merged**
