### PR TITLE
Refactored Join and Games Display

### PR DESCRIPTION
**Pull request by mattschmitter**

### CODE REVIEW

**Comment by ilyakrasnov** [comment]
Looks well - but can't be merged.. Please make sure to resolve the merge conflicts..

**Comment by mattschmitter** [comment]
Thanks for checking it out, we should be good now!

**Comment by ghost** [comment]
The game seems to be displaying for me now. For some reason I get the "You cant take your own piece!" error from the jQuery every time I try to move a piece. Are you guys getting that?

**Comment by tbowyer** [comment]
Hey Walley,  in your server console do you see any messages that might show why it's giving the alert?  I tried pulling Matt's branch down and everything looks good to me.  However, if you tried to merge it with your local master branch and test, make sure in routes.rb that it has 
put '/games/:game_id/:piece_id', to: 'pieces#update', :as => 'game_piece'

and not patch '/games/:game_id/:piece_id', to: 'pieces#update', :as => 'game_piece'

I changed it to put a couple of merges back and I think it just accidentally got overwritten in master.

Keep in mind we don't have specific error messages yet so basically if you see that alert "can't take your own piece", it simply means the AJAX request failed for whatever reason.  We will be adding specific messages this week.  Hope this helps.

**Comment by mattschmitter** [comment]
Good call Trevor, I replaced patch with put and it seems to be working for me now.  The turn based logic is working and got me a couple of times, though, since I was trying to move when it wasn't my turn.  I also updated the games index since I realized it wasn't showing all of the games that you could play.

**Comment by tbowyer** [comment]
Nice!  Yeah the turns threw me off as well at first. I'll take a look at all the new commits tonight and leave feedback if needed.  If everything looks good I'll merge it unless anyone else finds something.

**Comment by ghost** [comment]
Cool. So it was the route file. It's working fine on my end now.

**Pull request merged**
